# Generated by Django 6.0.5 on 2026-07-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='admissions/address/'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='admissions/birth/'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='previous_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='admissions/marksheets/'),
        ),
    ]
