name: Deploy SchoolMS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/schoolms
            git pull origin master
            pip install -r requirements.txt --break-system-packages
            python3 manage.py migrate --noinput
            python3 manage.py collectstatic --noinput
            sudo systemctl restart schoolms
            sudo systemctl restart nginx
            echo "Deployed!"